name: lint
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip pyinstaller wheel
          python -m pip install -r requirements.txt .
          python -m pip install -r requirements-dev.txt .

      - name: Run linting
        run: |
          sh ./scripts/lint.sh
